### ISSUE TITLE
Run the example

### ISSUE THREAD

**Issue by tinidoooooooog** [dipendra009/ElemNet#3]
Hey, developers
Would you please check the version of modules which are written in requirements.txt?
I've tried to run the example from scratch but no luck
numpy needs to be upgraded to the version at lease 1.13.2 in order to install the tensorflow of version 1.11.0

At last, I tried to install every module to the latest version except for the tensorflow (1.14.0)
I found the such error message from my Python 3.6.8 no matter on windows 10 or linux
`KeyError: "None of [Index(['H', 'Li', 'Be', 'B', 'C', 'N', 'O', 'F', 'Na', 'Mg', 'Al', 'Si', 'P',\n       'S', 'Cl', 'K', 'Ca', 'Sc', 'Ti', 'V', 'Cr', 'Mn', 'Fe', 'Co', 'Ni',\n       'Cu', 'Zn', 'Ga', 'Ge', 'As', 'Se', 'Br', 'Kr', 'Rb', 'Sr', 'Y', 'Zr',\n       'Nb', 'Mo', 'Tc', 'Ru', 'Rh', 'Pd', 'Ag', 'Cd', 'In', 'Sn', 'Sb', 'Te',\n       'I', 'Xe', 'Cs', 'Ba', 'La', 'Ce', 'Pr', 'Nd', 'Pm', 'Sm', 'Eu', 'Gd',\n       'Tb', 'Dy', 'Ho', 'Er', 'Tm', 'Yb', 'Lu', 'Hf', 'Ta', 'W', 'Re', 'Os',\n       'Ir', 'Pt', 'Au', 'Hg', 'Tl', 'Pb', 'Bi', 'Ac', 'Th', 'Pa', 'U', 'Np',\n       'Pu'],\n      dtype='object')] are in the [columns]` 

Would you please help me with this?
Thanks!

**Comment by dipendra009** [comment]
Hi,
We have updated the requirement.txt to match the exact package versions we are using to run all the code in this repository.

**Comment by WdBlink** [comment]
I have the same problem about the 
KeyError: "None of [Index(['H', 'Li', 'Be', 'B', 'C', 'N', 'O', 'F', 'Na', 'Mg', 'Al', 'Si', 'P',\n 'S', 'Cl', 'K', 'Ca', 'Sc', 'Ti', 'V', 'Cr', 'Mn', 'Fe', 'Co', 'Ni',\n 'Cu', 'Zn', 'Ga', 'Ge', 'As', 'Se', 'Br', 'Kr', 'Rb', 'Sr', 'Y', 'Zr',\n 'Nb', 'Mo', 'Tc', 'Ru', 'Rh', 'Pd', 'Ag', 'Cd', 'In', 'Sn', 'Sb', 'Te',\n 'I', 'Xe', 'Cs', 'Ba', 'La', 'Ce', 'Pr', 'Nd', 'Pm', 'Sm', 'Eu', 'Gd',\n 'Tb', 'Dy', 'Ho', 'Er', 'Tm', 'Yb', 'Lu', 'Hf', 'Ta', 'W', 'Re', 'Os',\n 'Ir', 'Pt', 'Au', 'Hg', 'Tl', 'Pb', 'Bi', 'Ac', 'Th', 'Pa', 'U', 'Np',\n 'Pu'],\n dtype='object')] are in the [columns]

How do you solve this problem?
